## web
server:
  port: 8080
  servlet:
    context-path: /ScheduledTask-core

## actuator
management:
  server:
    base-path: /actuator
  health:
    mail:
      enabled: false


spring:
  ## resources
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

  ## freemarker
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3309/scheduled_task?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    ## datasource-pool
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
      validation-timeout: 1000
  ## spring-mail
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    from: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

scheduledtask:
  ## access token
  accessToken: default_token
  ## 国际化
  i18n: zh_CN
  ## 快慢线程池的最大线程数
  triggerpool:
    fast:
      max: 200
    slow:
      max: 100
  ## 日志刷新时间
  logretentiondays: 30
## mybatis
mybatis:
  mapper-locations: classpath:/myabtis-mapper/*Mapper.xml






