server:
  port: 8080
  servlet:
    context-path: /xxl-job-admin

management:
  server:
    base-path: /actuator
  health:
    mail:
      enabled: false

spring:
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/xxl_job?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      auto-commit: true
#      一个连接idle状态的最大时长，单位毫秒
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
#      等待连接池分配连接的最大时长，超过这个时长还没有可用的连接则发生SQLException，单位毫秒
      connection-timeout: 10000
#
      connection-test-query: SELECT 1
      validation-timeout: 1000

  mail:
    host: smtp.qq.com
    port: 25
    username: 2382546457@qq.com
    from: 2382546457@qq.com
    password: 123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml


xxl:
  job:
    accessToken: default_token
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
